name: crypto_app
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  syncfusion_flutter_charts: ^20.1.48
  intl: ^0.17.0
  fl_chart: ^0.50.1
  sliding_up_panel: ^2.0.0+1
  dio: ^4.0.6
  get_it: ^7.6.4
  equatable: ^2.0.5
  dartz: ^0.10.1
  retrofit: ^3.3.1
  flutter_bloc: ^8.1.3
  shared_preferences: ^2.2.1
  json_serializable: ^6.7.1
  connectivity_plus: ^4.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0
  mockito: ^5.4.2
  build_runner: ^2.4.6
  retrofit_generator: ^4.2.0
  bloc_test: ^9.1.4


flutter:


  uses-material-design: true

  assets:
    - assets/
  #   - images/a_dot_ham.jpeg



  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
