import 'package:crypto_app/features/home/data/models/market_model.dart';

final marketModelExample = MarketModel(
    id: '1',
    symbol: '',
    name: 'name',
    image: 'image',
    currentPrice: 0.0,
    marketCap: 0.0,
    marketCapRank: 2,
    fullyDilutedValuation: 0.0,
    totalVolume: 0.0,
    high24H: 0.0,
    low24H: 0.0,
    priceChange24H: 0.0,
    priceChangePercentage24H: 0.0,
    marketCapChange24H: 0.0,
    marketCapChangePercentage24H: 0.0,
    circulatingSupply: 0.0,
    totalSupply: 0.0,
    ath: 0.0,
    athChangePercentage: 0.0,
    athDate: DateTime.now(),
    atl: 0.0,
    atlChangePercentage: 0.0,
    atlDate: DateTime.now(),
    lastUpdated: DateTime.now());
